#include "precomp.hpp"

using namespace std;

#pragma warning (disable:4455)

void MoveZeros(vector<int>& vals) 
{
	vector<int>::iterator it1 = vals.begin();
	vector<int>::iterator it2 = vals.begin();

	while (it2 != vals.end())
	{
		if (*it2 != 0)
		{
			*it1 = *it2;
			++it1;
		}
		++it2;
	}

	while (it1 != vals.end())
	{
		*it1 = 0;
		++it1;
	}
}

void TestMoveZeros()
{
	vector<int> v1;
	vector<int> v2{ 1 };
	vector<int> v3{ 0 };
	vector<int> v4{ 1,1,2,3,4,5,2,7 };
	vector<int> v5{ 0,0,0,0,1,0,0,0 };
	vector<int> v6{ 1,2,4,5,9,3,0,0 };
	vector<int> v7{ 0,0,0,0,0,0,0,0 };
	vector<int> v8{ 1,0,2,0,3,0,4,0,5,0,6,0,7,0,8,0,9 };
	vector<int> v9{ 0,0,0,0,0,1,2,3,4,5,6,7 };

	MoveZeros(v1);
	MoveZeros(v2);
	MoveZeros(v3);
	MoveZeros(v4);
	MoveZeros(v5);
	MoveZeros(v6);
	MoveZeros(v7);
	MoveZeros(v8);
	MoveZeros(v9);
}

bool CheckAnagram(const string& str, string::const_iterator beg, string::const_iterator end)
{
	if (beg == str.end())
		return false;

	--end;

	while (beg < end)
	{
		if (*beg != *end)
			return false;

		if (beg < str.end())
			++beg;
		else
			break;

		if (end > str.begin())
			--end;
		else
			break;
	}

	return true;
}

size_t PalSize(const string& str, string::const_iterator beg, string::const_iterator end)
{
	if (beg == str.end())
		return 0;

	if (end == str.end())
		--end;

	size_t res = 0;

	while (end != str.end())
	{
		if (*beg == *end)
			++res;
		else
			break;

		if (beg == str.begin())
			break;
		else
			--beg;

		++end;
	}

	return res;
}

string LongestPalindrome(const string& str)
{
	string::const_iterator beg = str.begin();
	size_t max = 0;
	string::const_iterator mbeg = str.end();
	string::const_iterator mend = str.end();

	while (beg != str.end())
	{
		string::const_iterator end = beg + 1;

		for (;end != str.end() && end <= beg + 2; ++end)
		{
			size_t size = PalSize(str, beg, end);

			if (size > max)
			{
				max = size;
				mbeg = beg - (size - 1);
				mend = end + (size - 1);
			}
		}

		++beg;
	}


	return string(mbeg, (mend == str.end() ? mend : mend + 1));
}


void TestPalindrome()
{

	//cout << LongestAnagram("") << endl;
	//cout << LongestAnagram("1") << endl;
	//cout << LongestAnagram("12") << endl;
	//cout << LongestAnagram("11") << endl;
	cout << LongestPalindrome("123") << endl;
	cout << LongestPalindrome("121") << endl;
	cout << LongestPalindrome("123454321sjkdfjs") << endl;
	cout << LongestPalindrome("wier123454321") << endl;
	cout << LongestPalindrome("sdf123454321gfh") << endl;

	cout << LongestPalindrome("a5Sn8PtU1yAZiGxIZFMI5VJZB8L7HkAE61DnsVQkxXRoBMCJPASirtXEuRkmEggT3iiMfgjUbVGPtZTb5BfSSnSYiSBnfuZBGMsrklEv7KG0iJvqQA5MJ5Mtba6IBAEkDOwK3ZGQAwF3eBoc1Yyxp1W4Ek2JctoP9uiBmnaOMbBEXXQF3tgbU7QWeJuYE73GQ5Ggs0qPPkDw45928juD2eqeRVSy5f4uWTU4Six8C2jrzH0KxwyUQAll0fWPWGLY5R1zMlJhP5ZcscB5VEyekfasSqXLLLY04DawIhbP7A18Xh5nnwizUbTus68jMnY8mMHERYzGXyX2YNa3BVxQp8KuCEDYO2D4Jiyjfc0DOoNhv4IAMzGr9JBSEMGIfBefNSZDlKRmXqQ4CbRbBe2bkV3A17JIhmEkHX9LlyWGy9wisXuLeNtFeY4VqAJ2iiNp7ko0hq7Y8SZwo5CWGGhZuRJMFHseWoJUk4wALx2WQLl6coujwwSAy4JeBGYGcm6yeE59N3YDkkMizY2e3rXwzN7UXgV3SSVqFrcqb9BXlqnj8Quauiz2vBCxfVTC5LYoOlh15IehfYELsqrKPQkOPkyANI5Jf3cDmlvkxPzFKBJ3nWsxuNrDzgHlRXjPDyR9xV1ikzIRgpieUPwwNk53fZM7BG2rtVweyYapjEpDFch6wnoolymTPFFy0Yg9rVpphyYn8465Sy5PJDZlKo6XtXDgLy4JDfxW70urOw4oTtuxSCFnyEnHhQnu2GF2UDQotsZ7OcbRHVxXSQKCfGFThRE0rQ8IL2z2rtFMYEhEN7qsQyk1SLkOuforXm7WKe5t5W1jDxIGz1UtwKH5pC4IsIwb2nBhLhCqVKSogt0ajvUbDeYECo7MpwfMAR52Z9m9ky2i9cGTYxZeicaqJFiKi1P6XCsoH82T4m0KJ9WfQVjFc6gZtJ4EwhV2yvEp0e4OiOCNlaxHXOBmHw3CqzBVeFF1NGAOSeuutR4TVVs1X6fqR7GWH9DJnClQAN82W4iyElh471wZEb28QJTtFxhE5cAvPMhjfKvIWfwlBtiRcNQMW9MeoJ2TsxFM3NrRqoENLt3ffWCOWaQAxU6ZGoI86hVF2u2mKfifnkihEIchYI0HyJMbUnsrrOADmpsScxe7Q3WIMAx13OnlhDyvOO2YNUC0Ixg0CYlvWEWvpjqYF5CGQ2DkRzasCNQMolAP50lBYZ7U14xEpq0bmESOBR201i84yazXtzWYvCXglcKyllTIVLKLiN2rpuMImbhworBU3wBEUsc0fFU5AHMP1xmqGq1he8K2jILyK7wZCUEixGKjQYzXtgCpMEXToyoR75VlbRKr5JJ8DoGqh96FR4yYqxDAg4EhcDLheQymZls2OrFbtTOeHa79MjoxLusD9bp00wNcFtWO0nhkmBtBA8UC161kfOY0xRE6ygFHGoOB5VfDnIBVH95MmnDF2aj3FvSVTficL1VMUOGh29ny4yHk1HNuOOkJr0qo4Nq82kOuDF7tJBtmos58rUWRkQ7TQbkx03GYMa4v3DAzgkhpaQGGOGLOCp978n5msFYOH6bsbKQY7qUOqVbYQVGvOXD2ghxyZPvCoFtrGoHgUJSkzhMYA3cC1JQUyBa8n1Hv8TR2byqnFjQsWFVW3UrfRBvzj1XvFtcSnM3c4io8Wq0eI17XBongsWr1kJP5bp1Rv00FJyWeYPsuYNFAcrJzRB8xQuvUAahGKeHb02TuTjLgGqbu2IE1UimCQA6tcrRyWET43x9yV4qimFVulmb8QI1ZoxBEXJX57cXkG1wKlYmwAgoTX5TCL0gygro8D6GsPMjDnESS5oB7IGzssWZe4aNTIsTavqwbbHmW5K9VrVVSBv4eTf3ygfvoZpw6VnQThEO7Hbq1MOji4xm1SzXPIgeYDnnb0z1mswOb1xVwC7XPk2VH6MJZmZwiL0EsRI3PBVHGgcUjj1bBYGz74ufG7mpPb90IUpxyneDc9Ch9aaVD3egtZ1eul4AizylLIYFrgk35hqFGEMtxiySua35XiQmZwCw19Ls1ok7fHcSgV0iIymi41upH2flWRyAMkaUmFvBDQ1Yycjin5w21EJL7M4BIkCvFtWlkbirJy5PuCR69QOBHs4V1OGfa8KOFBaSX1e6rwVOq89wTR4FQpr181vysz6Q4NFBvuveDga8phTTX9Ug1BQOqN0HwTzBKEUxlh0V84B6eUrnfQv8aRmXSrZVCMR412LTv4zSkJiA6zqSqwrBARYCZ8EpNLf3zuD0GWwe42x2XNgbcEj1JwH2vT8palW7IZaga7FQScBL4fiRPUK9x99KSz2wGzXReLOoatiE9kax7Amb1GBI0GYrpJhHXIjMTkT36RVGC4JT4cbCkkvefmBQZklw6VQgT4xj7kt1XknuCh1n9nTseUu0yCYsCvZaE3NHwY16eIbvXBwvs0kTHfA5RXzv67p1sMy0SDWFGhpGrOHLpyWYRuN5r0SnKGKJPUuo4DD4tjj442CVgRNmTKXFujP7grvmJii7yYXs9S5zasgZSKF5MWAeienG9CfuJC9o4UmsIKUN2oVs9x2a9aT4haLy5UJGcJL09BsoCEqT5U2A7OTup0J4B7U0Zce4PmJ0ow9Tf11HUhCpe2oXO5m9sic6n04prt0iYa0EHZuaHLqE1qR91ENSHFCYQ8MUXeOQxK3GRIGlDBDTb9y0zV3ZklFlCl7WnL5tHIZbAQQB3Khl3r7M4ONjMeA8fAftwwjwCZwsHqeiJDo3DzF4YxgwCVmEKxXtmR3sbMiYAGLLjBSjASFpRx3ASTtbGtOkzTnSjwre2XH5gFUIQtFLI59EV2AHTE4MkcefBMVA7zPylMzxZesATlOZXKuC3Go5T6LSx71EUXUBoqrIwPXDDp9WoTUWPU8w7HTtofCYIahxy8c8rLCNvLXzF3o2pZnEQmwzVGrfL8TjOYFTuHJyetzCToCyPPrIOM1VkNfYY7yljBRByQkaa1sc4Z5zOGtLtb1ISqGbIhf6loAHKf5efoSxMjIEsClAXLzfx5vTUIKz4aWW8Z5Izm2WVFyMGZpsGZVl0ms0cqwCD61buuuwIyuq8KTZCsMDZmUj7RozxmArCt2g3ngyey5Xi55MfYIFMXDMsu1sPGjC39yCVRZSMpCFDFuexziSrol4hs66ynHuQCymlFpohSSkKxUI8bFsaYjyYiCrRGILGs5cOVRc7hoQilMU1SSF86zkrN7gIDJu4LIZgNkJ3349fXoIj7tR1zCCGlJkGFZezHTsIENiVBzhA1Z3zZJzRJXzMXGRXg3YcqoeUgDpcvBovUYw7XSytZ6Ttyhzcr55c479b8c2XnSqI3aO2rLstaa4czateXRo9YqyrxGuFDxNpbU3CZ9zSctbZRNtm92I9zp2aRW2kP0f1zmNEoppSxTCGqOVOxFbZyLXvunOyu4Uto7tNzP3ryg2bmiiBXearM3uStFEH7uCfpeY1lcqUMm1HWQ0EXV2mrpSGLAaqaHIUCs8GSQFnYEssScqqUMfhW0LHYF6RTrPIyCmlCO1oDL4kPkEHg93hM5vcIbaJGuILBmyY5Gb58lGGZG26j2LW6OjQ2lbY5a1rgrgU7r9YRj46qPKCIXyieGrFUuc8fPNMszsWD1BZH3v97fanYRDZPxSmtLHhAO0TuvXQhneQ5qkWW2X0Crbn589Jgh5xSIJwnGgxSTr3IDjZhJ5fCEKXvuDBgHDr5Dh7qZXcc26NWzs57hgqxbCErgvs3YxUcYhTjAqpWTtAhqIwMYnBVSuAbrcWELTmD84ZabETlFArazFhfnVt1Ltmh7NYCFK2CEiPz4lcRvptsVEqc4hjMptw8eIzEcFv8PIpgFjXSyNN32vTcZ9MvJ3XIlSNyJwf336xJObL6nXF9CXJJcy06BmBxP6AMM0lr35aiOpDv6WYyLYbDoO4P8SyznyKNFWXLO08Yr3QicAuIZ78YjokXw55mDWtXsgvfZvLeCxmwUgNhs4MbTgrgry2Z9BAIuEGpA7JUZbhbnc4fJFfS7cfX0opRhVkf56DOT2rwB8w71ko1SWoD7gBmUMDPIFeF3S2OUKrSc4lr7hAM2i2HTzJ1vRqmjMq9CIjGpuZYrDiazl3EPtmaIyy3eeRve33zMFHuhbWy67j3C94PSKRpjzDBmEYYrsTPaY2ML5rYYhr62UE4tyHJtstb3sCteZV71qPQNt8GqsqILXcBUcMt8Ow30xYqS7x6oNL2RYazTs604s2AwqXXpM2voOOFSJUCCtPvMI3l5tiCVzCV2nAUNxncQBKuzqmEgl0smKEAuh9n6exIbwEpxwIa6Zp8lMKPLvUVYknPxak75hqLPj1m8T8uqiI1pcej6fvDHg3z1bgbiQQlSmD8cEFa0DNrc0oAaZ7VE5NNOLGGp2jCGz9rFYPb5fnzlIZmU8ui43m0ZeNwFmic53un6rWmTTxFG372aBwB8mqvyogUwAhPMbGJOhZO70BeYUcuF0t5s3rmRNo5FUGTIm049mvzCx3OTw8TxDBNCgZqpDUVYD5Voh4F6pYuYk5jFS5hSXWuCDDkgjfYj74GcO4ZNUqFVjaN35oOr2Gm7aeuxNMeMKiiLMW5XVRoVREA30cEAx4y5Oh3THboaW7xxcOJwRwnaXDMxXovwPchiUPaMZI04X2LESazavfB0eaPhia9IUP29pVxKR2UQXXSbOu5e3tJviDcQKXrMasPICuTjeeLLEJoo8AzJngioHoHSGAD8NWBJ7EBcIy44lVr8geYSc8WEwazRcwY7JonK04Xt8m80vNI7k1EIujgoXzz1QvwvVRpiqp04xnV8by3YYKpRQSWFFBzguIsTsh4vG8ucxmamCubhHO124M1laU2PfCGMQU6nZbwo8N3X1apR02ExBEelP0ZcG7ItKjScLh44n0kJrFo0CWYTSXPr7HBDE3tH1BQgaTveEaN2DAunQM22L7YfawBGsGQzeozc76XhSpyhelp2JbFsNHmakYkAU86XAekTwxasPBqrWK56A6oxCzvlFrHtOc6ciYGHRzg8huYvcm1DYfk4su5tnPD5STt24XbJ6srlKFpkPZM53t1OCCkQDT4LlN1I0CalQ3QMn7f05BefSOQrzhuLrLNjh6015tSFWjOl1yLWtPOvx5Cg54xkeLxGiM4lxwl2MoLUkUfIwz677ThggkVj4IwTYN6x7qguNh0qDw0hZcBjikiLp6S8g6PNmrmctvTJYYBPf74uNLihf9nT2nCMNwiZeWO1WDyuAMk5RvHeBb6RlBVE1onnjrLzFLttsTJ9EhlcrYuV4mQxiGoLfA2RnSB9L7tMQzPfv5qB8hxIcEoGjQeA6bRAr0nEDl7ofQQzalhrztxzFFYRn8x8UyDn6Uu4rYtQjr7MTqxGYY8GTNOc6t2v2faCFTBWWyCSD9m4uG1UYttcb1ZysQsj6RhyaHJLEH33nHYD8S45WqfClNK7IyvMHYkxI7FKeRTnb7JbFSFMzznFlpbKTD5AoR6ajjXxGv62ap7tRtQNVlvJCtgX2uL57ST4MwQNgOHfxmBRAmjKm1NixWmhHi0hSkBSaYHJuzDE7plYgjzgUYBz8APSfODT7qGAzqFKsRHUmX2PH08aFGVxtTBabqWeo27Mj3E4O55B9mNFWWItZEYhAfQqNMwQFVOIO0m2RPLhHceumMsNPYwPIqAle3oWxIzM2V9sP3LC08JjSgRpj4zm4uLR68LK253AnhTbX1ubLInzR8JDfEmwz9XtpPwnM76qJPOXoWNgCmQmpenrOvGoK3fOYo7Bg9UsoKFY8IK45C9GxD8gZcwCrZNKOb9Xg4MGrQDasAT8YIYAX5ZSxqPkvTkgO3lV25pBfgN6oMrBkQrQPeJWAn2OWDY4oAa3u9FiCBJeZVl4v9QNf0eYQ3a5kbwuySVM7B3TqWown8bjkmSDMfSAPna6ZQcF7xMmbH1BZw2cJFAQWjZL46CMjstr4DB5JxKJSOEeeVvEGI0pE4flpVDwYNxpvwiEP7bnkj5RMGBYOYvoiKTqgrsAehTDv4wWThtVkgRmYhYiYXv2kwEqmaAWhWDFS4JDJDj8hVjjYYVu5MSmbO1Lj8LgsmT4jVRPpE7c7Yk7pH3LAq685ronSEtQAzP2UmnSg4WpBlSIGYxuObc07FfpjzaVN2x2MM3NpLywC2oD9DsmyFwhK776R8z04K42up01cXzDKcuuAzZLkJKuy5oQD6hwBAKpGEAj1cWKzLMLBiGSDpqNvcDOxZfxwYcJDnOHlhzqjh7m0sorhyZZqVOsBj5er8BPZ7tFwXfFgrBCn9lJ3L1i11rjcA9nOG5OfzY5O2SlwivySQHO59vbcszs7o9piOuS8bNqAXJAV2xkQtBwh0H9Akj81YqFGNsw4MuXa6D6R9ZDx0HygQIsAso6h0FJoMVgzD8rDSknouicE9YcmnmSgTKA1rF013F0TgqFhgGvoUNfGmODEqiaaNB10Izm1KmJN12mnlulZu6WaYloJuZkUbO0lmBpzDrIxzsWfAUFWcbc02f1SqkAjIQ5tyJEAoj4cP22wyjN6SVR5Hv0XkoB7Keujws7ZrcZ4EkiW6HavsCLDWkm0u09YAJHmt2hPwbEJrjKAFH5XvMSacLWL3PhyGGivKyVGv1Spi6QmUyM0qRouPkV32ZVwWOQfHuaXx0zfZQAfU8uQImcC0rkJv9NV2MN6wIYm3Oi3sikAcUM6hntLDHqxlKataweLi4FKn3262SC7b5cgT3PVgJQgxJ7gFqA16OHcZnA0GHuxBlkqvGjZOOyB2KYlY132XxJut0mP3TvuQYENAeNMj4OMDgi7MnlXh6XFk2V1MKKPgQEXfOWhUFf0kPX6PqRNLA9BmtPBKw8BpaBbCzHz5lr3Beh8DbPu2lNTEQ8gp6Gz6EgFhHigR9W16aIskSj4mwxeCZbRTrj3h5ZS1yNUnArSRAIwM8Tiabb5UPrSBSxt27tf4cIlM7YzLpFG8AR305rAYngjYz49nsuVAPbxswywLcjwRwl5TFxHTuyFDvfrP5erONn8Jq3KvteAY49OXVEjtnCZTQyRi6VXlDIpgM2K5heocSaroQyECJBTpGWFa889HyVFHmsi7xRmqFagR2aeoqH6mJCKFlcpfaw6yaqjOkJoI5KEmwbYmsEODL6sYfMhm43i89ETCMJZIfHvXG8pa4vImWM0jQy586RlRWoHy9BtVey803EbxJEg0vbrbjygZQtZGmqypQQB6XbB9Q0EgnmpknzPMUKLbwFhuj0OOIHR0Ef9ef6gsmmauI3YjPWotQXh5QxCjkoD5rmRtUzizaCmaRkRcAIrhagXu51fVWDgzgx4NYF3il76S73OLHfV7wmnauCpMGOyAlvlMfabDIRx6xNtYQPVDJlZtvuVwLhLby6v6i65g0JEGJmme9Gcis36sml1zqHDmUZ4N6ZtjgzFKF13kIXAeyhFUCWXLRrYKsqRiLCEbZjPz7L5KOtuSxnvJ7mUI5oHABppShCczkGMDjVaaYGaEBH5bMYGCCb3gHhaoxEnFH0fO1C2IXaiCb9lCu82IMyg7oOWV6V1gDuDpP3aV1VF8U3WrKoiYMmz0xTGpZrTsbemSaxB1Fi1yb3Qte75S5TuYxNCnHvrQO9kkhOTLXV93IW8oO4VkDaV6ZvvSDU28rBLMgJ6KSDurvhZMHaE43wMW477oRxtWfNVyRCYsrMB7vAQvRWlNgi8fAbB2n8QWsAQueeGp80tLoe9fVvggSrekuwz7j5P8ktnOwHhOm7JXYVq2K7KS7bASDIsiLGw5E4rxv2J69MXyXMXjor4v1hYxK6mlnoNGsilcwPBXfTI0R0TjWWWOCJFgJm0O2DZOrlC2q0Y34Wi7q4FbM3UFxuRuGezG3tNJwaXxC1Vm4gpeQPYXF65xW7DyumfS2ufILPf8Hfx8h6sYePXLILHyMe9p2S9KTLPxkFA40fzjPffY3WQcEhgW43mhlOYJ2S99DkLXxVQiC61RBhDJz8sFw1OOR9K5opwEFeD9cbYaVngKQyEmKlCNJW917i45QQ7GsmuF17zEGQzoYlpfIFaniN1fvQwPTIYhesBMT5oCUtXrCxM0k51GQo08QTJ50tT4PWtMWtAv5ssqJKu9HzgDlTGzweMm2ss6BXWiCrKEhWc5U9FZfn5FcGwUVpkG7BDwAMyvqk6XJzqBncjbqYy4e8iLxbPo2HXAvtfOxpTRO5f31SM40r6raSwn9ORIqr15V2tbXIFNuiAa0Zx0HNS1pI86ZRMvnvtIqaC3wrsXnRVG5tH2Yv95h3IiPpIj5kYeADW1scgyEb6kAFvXTtI6FOPX034qQtbrVL4BUaPvOZibIgQf0E3B8ZbP5CTTntWNCFRhaBTVLfDSolQJb019tYRIcyV6AWLwUAx6gUUpmQ2tNirOHwfVVm5BD4HqO8pnyqzPWHCzPr7QYQycSJq0B4afJTBnH537GDVL8BNcbFXyb036xgs2cU2P3WDTxjklNb7WNQwkwztBgNa4EEJAGPsVMTJqcBUCrehplhUE0LI0QZYxA4TLCzmayyibcSm0ruOEyBIbgCJ2AlLe9uPjNUy1QcMRWwplBQs2KN72bA7m7JBJITxi9NfbS8P6lXqfJzrpLhxOT2pexOvD6S2l4UzN0rmpsgXKGtUWQK5DJqTuoEowRQ0bqm7Ak59bqRCZFtSJKmjXSOLZcIWUJ6hq5jtM8wAOqm3T9nmcARXUJVVF23U3L7RKAbHRv3iaPJ8wPHPajVHSFqrPDrnp5tD3w8yjLwMUjnk7JERHG8LHxtXXf5xxpDLt33jqnQK8jeg4amcgaayDgHOcQWAl6E54kun1ZuKcQjapzkR101MyqBuWzz5xn4CfVWBOcRKJyqWCF7qhL4pRMr6gqKaCfBQgmLk1bFD5p83HVl1q821W4nG7mlL0FbavGTP1XDFvmuuMOnE0Z2GWso7A2NmKLngfDDlw20Tv0iWjYzROSPfyL7VWz0lDXzur3G28WaJMN3G5EDijRPUNzZZPmnq3fOSBBHXzMPFM11OzDXTuCqDRrpe9T1yIo1RGp3wA6b9JmXMBpGDberUjWlHXBwEp6EEasJPnSIy0ByIzyA0MDnOFEFVuKXD27vhUcl28RzHol8faFE3wOLARixB8V8P1knGfMObPUveDe8A9Q0B56a6qU3bFjC1DRGQZzUu38fHWVotJnN3S5vjvRHm00EkeSixULe8AoYRUMRIK6b2yK8kBOQqlZw9OVe5FbkMp0TbquAIAmtjAPz5122qX6ISNcissecU9zSchn41TgyT5X24xcYzU2VrybqAiWL18iclSUYhsJxJfNpwr1nGhbONP6B2ch5QTQC5SFwpNkIbPLmHrTzO1lK0n5ZEVN0gAGRXnQirFnVgknLGi6lGLHrUDvMgRxVxLTFRKX1rHshK8BWwAuVJDc8cI6pVwCxF0waFPgH2tD1lSwizZfNiuCZTFxmRDb2f9DOigo4Vl7j8v4EZ0Q1Q0YejUreSe13QEVD1AutVuRsmiZ15GT248TpMW9TSEpZlmw4YKtgaMMssK7eaHegDAw7k9nZ2NrEkb2ci7LJ7hfYaiSV81THLpQwcrjoWcUV2ag2f8FqBLnprRuxgI6l0supySnh8Ax4DUIrXjFtegGDhoSbzsrbvhI4W5LK1rSogGaKlcsBb4fYGZXCAJnSRNux7S3S9VM3fFk1EtzuLJ25T51Iw1lV1AyRCVJtTHWXo65F6oSa3xYwi2cmL5mrD5KADl1P5R3CxshkLaIpMDfwxTn1W1pxJjA1FtDJIGX0WVZcP4iz6UFehCBmnBpjvzvZIrfIzegNr9O5kgc3qe4Go56mAgwOQ7lJs2uCMUgPO0L8RNQYaY5n1bNh9H6EJnmWtxKOsjcMEfEAMh9wOnkxSmv501iol5y1YHlSkv9I5mcuFgMvwZJqVIKjvkUryBhu0sEmaqtWvOYy7NN5eMi1MRssi6JleAQgX8Uo1M") << endl;
	cout << LongestPalindrome("abababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababab") << endl;
}

